from typing import Dict, Generator, List

from google import genai
from google.genai import types

from app.config.settings import GEMINI_API_KEY
from app.services.web_search_service import web_search


# ---------------------------------------------------------
# Gemini Client
# ---------------------------------------------------------

client = genai.Client(
    api_key=GEMINI_API_KEY
)


MODEL_NAME = "gemini-3.5-flash-lite"


# ---------------------------------------------------------
# System Instruction
# ---------------------------------------------------------

SYSTEM_INSTRUCTION = """
You are a helpful general information assistant.

Your responsibilities:

- Answer questions clearly and accurately.
- Explain difficult concepts in simple language.
- Give examples when useful.
- If you are unsure about something, say so.
- Do not invent facts.
- Keep responses structured and easy to understand.

Web search:

- Use the web_search tool when the question requires
  current, recent, changing, or web-based information.
- Do not use web search for questions that can be answered
  reliably from your existing knowledge.
- When you use web search, base your answer on the
  information returned by the tool.
- Do not claim that you searched the web if you did not.
"""


# ---------------------------------------------------------
# Web Search Tool Definition
# ---------------------------------------------------------

WEB_SEARCH_TOOL = types.Tool(
    function_declarations=[
        types.FunctionDeclaration(
            name="web_search",
            description=(
                "Search the internet for current or "
                "relevant information. Use this when "
                "the user asks about recent events, "
                "current information, news, prices, "
                "latest versions, weather, or information "
                "that may have changed."
            ),
            parameters={
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": (
                            "A concise web search query."
                        )
                    }
                },
                "required": [
                    "query"
                ]
            }
        )
    ]
)


# ---------------------------------------------------------
# Build Gemini Conversation
# ---------------------------------------------------------

def build_contents(
    message: str,
    history: List[Dict[str, str]]
):
    """
    Build the conversation that will be sent to Gemini.
    """

    contents = []

    # Add previous conversation history.
    for item in history:

        contents.append(
            types.Content(
                role=item["role"],
                parts=[
                    types.Part(
                        text=item["content"]
                    )
                ]
            )
        )

    # Add the current user message.
    contents.append(
        types.Content(
            role="user",
            parts=[
                types.Part(
                    text=message
                )
            ]
        )
    )

    return contents


# ---------------------------------------------------------
# Execute Tool
# ---------------------------------------------------------

def execute_tool_call(
    function_call
):
    """
    Execute the tool requested by Gemini.
    """

    if function_call.name != "web_search":

        return {
            "error": (
                f"Unknown tool: "
                f"{function_call.name}"
            )
        }

    # Get the search query generated by Gemini.
    query = function_call.args.get(
        "query"
    )

    if not query:

        return {
            "error": (
                "Search query was not provided."
            )
        }

    print(
        f"\n[TOOL] web_search: {query}"
    )

    # Execute Tavily web search.
    result = web_search(
        query
    )

    print(
        "[TOOL] web_search completed"
    )

    return result


# ---------------------------------------------------------
# Add Tool Result Back To Gemini
# ---------------------------------------------------------

def add_tool_result(
    contents,
    response,
    function_call,
    tool_result
):
    """
    Add Gemini's function call and the tool result
    back into the conversation.
    """

    # Add Gemini's function-call message.
    contents.append(
        response.candidates[0].content
    )

    # Create the function response.
    function_response_part = (
        types.Part.from_function_response(
            name=function_call.name,
            response=tool_result
        )
    )

    # Send the tool result back to Gemini.
    contents.append(
        types.Content(
            role="user",
            parts=[
                function_response_part
            ]
        )
    )


# ---------------------------------------------------------
# Normal Response
# ---------------------------------------------------------

def generate_response(
    message: str,
    history: List[Dict[str, str]]
) -> str:
    """
    Generate a complete Gemini response.

    Gemini can request the web_search tool.
    """

    contents = build_contents(
        message,
        history
    )

    # Agent loop.
    while True:

        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=contents,
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_INSTRUCTION,
                tools=[
                    WEB_SEARCH_TOOL
                ]
            )
        )

        function_call = None

        # Check whether Gemini requested a tool.
        for part in response.candidates[0].content.parts:

            if part.function_call:

                function_call = (
                    part.function_call
                )

                break

        # -------------------------------------------------
        # No tool call
        # -------------------------------------------------

        if not function_call:

            if not response.text:

                raise RuntimeError(
                    "Gemini returned an empty response."
                )

            return response.text

        # -------------------------------------------------
        # Tool call
        # -------------------------------------------------

        print(
            f"[GEMINI] Tool requested: "
            f"{function_call.name}"
        )

        tool_result = execute_tool_call(
            function_call
        )

        # Send the result back to Gemini.
        add_tool_result(
            contents=contents,
            response=response,
            function_call=function_call,
            tool_result=tool_result
        )


# ---------------------------------------------------------
# Streaming Response
# ---------------------------------------------------------

def generate_stream(
    message: str,
    history: List[Dict[str, str]]
) -> Generator[str, None, None]:
    """
    Generate a response through the existing streaming
    endpoint.

    Tool calls are handled first.

    Once Gemini has enough information, the final
    response is returned to the frontend.
    """

    contents = build_contents(
        message,
        history
    )

    # Agent loop.
    while True:

        response = client.models.generate_content(
            model=MODEL_NAME,
            contents=contents,
            config=types.GenerateContentConfig(
                system_instruction=SYSTEM_INSTRUCTION,
                tools=[
                    WEB_SEARCH_TOOL
                ]
            )
        )

        function_call = None

        # Check whether Gemini requested a tool.
        for part in response.candidates[0].content.parts:

            if part.function_call:

                function_call = (
                    part.function_call
                )

                break

        # -------------------------------------------------
        # Final response
        # -------------------------------------------------

        if not function_call:

            if not response.text:

                raise RuntimeError(
                    "Gemini returned an empty response."
                )

            yield response.text

            return

        # -------------------------------------------------
        # Execute tool
        # -------------------------------------------------

        print(
            f"[GEMINI] Tool requested: "
            f"{function_call.name}"
        )

        tool_result = execute_tool_call(
            function_call
        )

        # Send tool result back to Gemini.
        add_tool_result(
            contents=contents,
            response=response,
            function_call=function_call,
            tool_result=tool_result
        )

